using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AMT_RVMATGenerator.src
{
    static class Writer
    {
        public static void GenerateRVMAT(RVMAT txt, bool overwrite)
        {
            if(File.Exists(Path.Combine(txt.path, txt.name + ".rvmat")) && !overwrite)
            {
                Console.WriteLine("Allready existing rvmat for {0} and not allowed to overwrite", txt.name);
                return; //if the file already exist and no overwrite is selected we don't generate a new file
            }

            try
            {
                using (var writer = new StreamWriter(Path.Combine(txt.path, txt.name + ".rvmat"), false, Encoding.UTF8))
                {
                    writer.WriteLine("//Generated by AMT RVMAT GENERATOR");
                    writer.WriteLine("Time: {0}", DateTime.Now);
                    writer.WriteLine();
                    writer.WriteLine();

                    writer.WriteLine("#define _ARMA_");
                    writer.WriteLine("ambient[] = {1.5,1.5,1.5,1};");
                    writer.WriteLine("diffuse[] = {0.5,0.5,0.5,1};");
                    writer.WriteLine("forcedDiffuse[] = {0,0,0,0};");
                    writer.WriteLine("specular[] = {0,0,0,0};");
                    writer.WriteLine("specularPower = 1;");
                    writer.WriteLine("emmisive[] = {0,0,0,0};");
                    writer.WriteLine("PixelShaderID = \"NormalMapDiffuse\";");
                    writer.WriteLine("VertexShaderID = \"NormalMapDiffuseAlpha\";");
                    writer.WriteLine("class Stage1");
                    writer.WriteLine("{");
                    writer.WriteLine("\ttexture = \"{0}\";", txt.fileNopx);
                    writer.WriteLine("\tuvSource = \"tex\";");
                    writer.WriteLine("\tclass uvTransform");
                    writer.WriteLine("\t{");
                    writer.WriteLine("\t\taside[] = {10,0,0};");
                    writer.WriteLine("\t\tup[] = {0,10,0};");
                    writer.WriteLine("\t\tdir[] = {0,0,10}");
                    writer.WriteLine("\t\tpos[] = {0,0,0");
                    writer.WriteLine("\t};");
                    writer.WriteLine("};");

                    writer.WriteLine("class Stage2");
                    writer.WriteLine("{");
                    writer.WriteLine("\ttexture = \"{0}\";", txt.fileCo);
                    writer.WriteLine("\tuvSource = \"tex\";");
                    writer.WriteLine("\tclass uvTransform");
                    writer.WriteLine("\t{");
                    writer.WriteLine("\t\taside[] = {10,0,0};");
                    writer.WriteLine("\t\tup[] = {0,10,0};");
                    writer.WriteLine("\t\tdir[] = {0,0,10}");
                    writer.WriteLine("\t\tpos[] = {0,0,0");
                    writer.WriteLine("\t};");
                    writer.WriteLine("};");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw;
            }
        }
    }
}
